spring:

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:search_service}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: true

  app:
    search:
      threshold: 0.4
      limit: 20